export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const SALE_REPOSITORY = Symbol('SALE_REPOSITORY');
export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const UNIT_OF_WORK = Symbol('UNIT_OF_WORK');
export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const LOGGER = Symbol('LOGGER');
